# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "rhel63min"
  config.vm.box_url = "http://leleupi.its.yale.edu:8181/PKG/rhel63min.box"

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = false

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.vm.define :server1 do |s1|
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. 
    s1.vm.network :forwarded_port, guest: 8101, host: 8101
    s1.vm.network :forwarded_port, guest: 8181, host: 8181
    s1.vm.network :private_network, ip: "192.168.33.10"

    s1.vm.provision :chef_solo do |chef|
      chef.cookbooks_path   = "../chef-repo-yu/cookbooks"
      chef.roles_path       = "../chef-repo-yu/roles"
      chef.data_bags_path   = "../chef-repo-yu/data_bags"

  
      chef.add_recipe "recipe[misc::hosts]"
      chef.add_recipe "recipe[jdk::default]"
      chef.add_recipe "recipe[yum::satellite]"
      chef.add_recipe "recipe[amq::default]"
  
      # You may also specify custom JSON attributes:
      chef.json = { 
                    :misc => {  :hostname => "server1" },
                    :yum => {     :satellite => { 
                                    :certurl => "http://vm-satprdapp-01.its.yale.edu/pub/RHN-ORG-TRUSTED-SSL-CERT"
                                  },
                                  :gpgcheck => "0"
                            },
                    :jdk => {  
                                :tmpdir     => "/vagrant/src",
                                :jdk_url    => 'http://leleupi.its.yale.edu:8181/PKG/jdk1.6.0_33.tar.gz',
                                :jdk_file   => 'jdk1.6.0_33.tar.gz',
                                :java_home  => '/usr/local/jdk1.6.0_33'
                              },
                    :amq => {  
                                :user     => "vagrant",
                              }
                  }
    end
  end
end