# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.define :esb1 do |esb1_config|
    esb1_config.vm.box = "centos62min"
    esb1_config.vm.box_url = "http://leleupi.its.yale.edu:8181/PKG/centos62min.box"
    esb1_config.vm.customize ["modifyvm", :id, "--memory", "512"]
    esb1_config.vm.forward_port 22, 2222
    esb1_config.vm.network :hostonly, "192.168.1.10"
    esb1_config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "../chef-repo-yu/cookbooks"
      chef.roles_path = "../chef-repo-yu/roles"
    
      chef.add_role "esb-vagrant"
      
      # You may also specify custom JSON attributes:
      chef.json.merge!({
                          :misc => {  :hostname => "vagrant-centos-62" },
                          :java => {  
                                      :tmpdir     => "/vagrant/src",
                                      :jdk_url    => 'http://leleupi.its.yale.edu:8181/PKG/jdk1.6.0_33.tar.gz',
                                      :jdk_file   => 'jdk1.6.0_33.tar.gz',
                                      :java_home  => '/usr/local/jdk1.6.0_33'
                                    },
                          :fuseesb => {  
                                      :tmpdir   => "/vagrant/src",
                                      :user     => "vagrant",
                                      :url      => 'http://leleupi.its.yale.edu:8181/PKG/fuse-esb-full-7.0.1.fuse-084.tar.gz',
                                      :file     => 'fuse-esb-full-7.0.1.fuse-084.tar.gz',
                                      :install  => '/usr/local/fuse-esb-7.0.1.fuse-084'
                                    },
                          :jenkins => { :jenkins_user   => "vagrant" },          
                      })
     end
  end
  
  config.vm.define :esb2 do |esb2_config|
    esb2_config.vm.box = "centos62min"
    esb2_config.vm.box_url = "http://leleupi.its.yale.edu:8181/PKG/centos62min.box"
    esb2_config.vm.customize ["modifyvm", :id, "--memory", "512"]
    esb2_config.vm.forward_port 22, 2223
    esb2_config.vm.network :hostonly, "192.168.1.11"
    esb2_config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "../chef-repo-yu/cookbooks"
      chef.roles_path = "../chef-repo-yu/roles"
    
      chef.add_role "esb-vagrant"
      
      # You may also specify custom JSON attributes:
      chef.json.merge!({
                          :misc => {  :hostname => "vagrant-centos-62" },
                          :java => {  
                                      :tmpdir     => "/vagrant/src",
                                      :jdk_url    => 'http://leleupi.its.yale.edu:8181/PKG/jdk1.6.0_33.tar.gz',
                                      :jdk_file   => 'jdk1.6.0_33.tar.gz',
                                      :java_home  => '/usr/local/jdk1.6.0_33'
                                    },
                          :fuseesb => {  
                                      :tmpdir   => "/vagrant/src",
                                      :user     => "vagrant",
                                      :url      => 'http://leleupi.its.yale.edu:8181/PKG/fuse-esb-full-7.0.1.fuse-084.tar.gz',
                                      :file     => 'fuse-esb-full-7.0.1.fuse-084.tar.gz',
                                      :install  => '/usr/local/fuse-esb-7.0.1.fuse-084'
                                    },
                          :jenkins => { :jenkins_user => "vagrant" },          
                      })
     end
  end

   config.vm.define :mc1 do |mc1_config|
    mc1_config.vm.box = "centos62min"
    mc1_config.vm.box_url = "http://leleupi.its.yale.edu:8181/PKG/centos62min.box"
    mc1_config.vm.customize ["modifyvm", :id, "--memory", "1024"]
    mc1_config.vm.forward_port 8107, 8107 # HTTP
    mc1_config.vm.forward_port 22, 2224
    mc1_config.vm.network :hostonly, "192.168.1.5"
    mc1_config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "../chef-repo-yu/cookbooks"
      chef.roles_path = "../chef-repo-yu/roles"
    
      chef.add_recipe "java"
      chef.add_recipe "misc"
      chef.add_recipe "fusemc"
      
      # You may also specify custom JSON attributes:
      chef.json.merge!({
                          :misc => {  :hostname => "vagrant-centos-62" },
                          :java => {  
                                      :tmpdir => "/vagrant/src",
                                      :jdk_url   => 'http://leleupi.its.yale.edu:8181/PKG/jdk1.6.0_33.tar.gz',
                                      :jdk_file  => 'jdk1.6.0_33.tar.gz',
                                      :java_home => '/usr/local/jdk1.6.0_33'
                                    },
                          :fusemc => {  
                                       :tmpdir => "/vagrant/src",
                                       :user => "vagrant"
                                     }
                      })
     end
  end
end