# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos64min"
  config.vm.box_url = "http://leleupi.its.yale.edu:8181/PKG/centos64min.box"
  config.vm.customize ["modifyvm", :id, "--memory", "2048"]

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  
  # JBoss node00 ports
  config.vm.forward_port 8080, 8080 # HTTP
  config.vm.forward_port 8440, 8440 # HTTPS
  config.vm.forward_port 8780, 8780 # DEBUG
  
  # JBoss node01 ports
  config.vm.forward_port 8180, 8180 # HTTP
  config.vm.forward_port 8441, 8441 # HTTPS
  config.vm.forward_port 8781, 8781 # DEBUG
  
  # Jenkins HTTP
  config.vm.forward_port 8888, 8888
  
  # SSH
  #config.vm.forward_port 22, 2222
  # Enable provisioning with chef solo, specifying a cookbooks path (relative
  # to this Vagrantfile), and adding some recipes and/or roles.
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../chef-repo-yu/cookbooks"
    chef.roles_path = "../chef-repo-yu/roles"
    chef.data_bags_path   = "../chef-repo-yu/data_bags"
    
    chef.add_role "iam-vagrant"
  
    # You may also specify custom JSON attributes:
    chef.json.merge!({
                        :misc => {  :hostname => "vagrant-centos-62" },
                        :jdk => {  
                                    :tmpdir => "/vagrant/src",
                                    :jdk_url   => 'http://leleupi.its.yale.edu:8181/PKG/jdk1.6.0_33.tar.gz',
                                    :jdk_file  => 'jdk1.6.0_33.tar.gz',
                                    :java_home => '/usr/local/jdk1.6.0_33'
                                  },
                        :jenkins => { :user => "vagrant" },
                        :mysql => {
                                    :server_root_password    => "vagrant",
                                    :server_repl_password    => "vagrant",
                                    :server_debian_password  => "vagrant",
                                    :bind_address            => "0.0.0.0"
                        },
                        :maven => { :repositories => ["http://repository.its.yale.edu/maven2/repo"],
                                    :version => 2
                                  },
                        :iam => {   :tmpdir => "/vagrant/src",
                                    :radiantone => { 
                                              :rpm_source => 'http://leleupi.its.yale.edu:8181/PKG/radiantone-vds-ics-6.0.2-1.x86_64.rpm',
                                              :user => "vagrant"
                                            } 
                                },
                        :jboss => { 
                                    :tmpdir => "/vagrant/src",
                                    :keystore_url => "http://leleupi.its.yale.edu:8181/PKG/server.keystore",
                                    :jboss_url   => 'http://leleupi.its.yale.edu:8181/PKG/jboss-eap-5.1.2.tar.gz',
                                    :jboss_file  => 'jboss-eap-5.1.2.tar.gz',
                                    :jboss_home  => '/usr/local/jboss-eap-5.1/jboss-as',
                                    :additional_deploy_dirs => [ '${jboss.server.home.url}webapps' ],
                                    :nodes => {  :node00 => { 
                                                              :user => "vagrant",
                                                              :maxperm => "256",
                                                              :minheap => "1024",
                                                              :maxheap => "2048",
                                                              :additional_jboss_opts  => [ '-Djboss.proxyname=localhost','-Djboss.proxyport=8440'],
                                                              :additional_java_opts   => [ '-Xdebug',
                                                                                           '-Xrunjdwp:transport=dt_socket,address=8780,server=y,suspend=n' ],
                                                              :additional_jboss_libs  => {
                                                                                            'cas-client-core.jar'       => 'http://leleupi.its.yale.edu:8181/PKG/20120703.cas-client-core.jar',
                                                                                            'cas-client-jboss.jar'      => 'http://leleupi.its.yale.edu:8181/PKG/20120703.cas-client-jboss.jar',
                                                                                            'mysql-connector-java.jar'  => 'http://leleupi.its.yale.edu:8181/PKG/20120703.mysql-connector-java.jar',
                                                                                            'ojdbc6.jar'                => 'http://leleupi.its.yale.edu:8181/PKG/20120703.ojdbc6.jar'
                                                                                          }
                                                            },
                                                  :node01 => { 
                                                              :user => "vagrant",
                                                              :additional_jboss_opts  => [ '-Djboss.proxyname=localhost','-Djboss.proxyport=8441'],
                                                              :additional_java_opts   => [ '-Xdebug',
                                                                                           '-Xrunjdwp:transport=dt_socket,address=8781,server=y,suspend=n' ],
                                                              :additional_jboss_libs  => {
                                                                                           'cas-client-core.jar'       => 'http://leleupi.its.yale.edu:8181/PKG/20120703.cas-client-core.jar',
                                                                                           'cas-client-jboss.jar'      => 'http://leleupi.its.yale.edu:8181/PKG/20120703.cas-client-jboss.jar',
                                                                                           'mysql-connector-java.jar'  => 'http://leleupi.its.yale.edu:8181/PKG/20120703.mysql-connector-java.jar',
                                                                                           'ojdbc6.jar'                => 'http://leleupi.its.yale.edu:8181/PKG/20120703.ojdbc6.jar'
                                                                                         }
                                                              }
                                              }
                                  } 
                    })
   end

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder "jboss-apps", "/usr/local/jboss-apps", "./jboss/jboss-apps"
  config.vm.share_folder "jboss-logs", "/var/log/jboss", "./jboss/jboss-logs"
  config.vm.share_folder "jboss-deploy", "/usr/local/jboss-deploy", "./jboss/jboss-deploy"
  
end